// Restoring the built-in delegation tool exactly as documented in
// docs/concepts/built-in-tools.md (`### agent`) and as generated by
// `eve add tool/agent`.
export { default } from "eve/tools/agent";
